language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script:
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.6.0"
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.6.0"
      gemfile: .gemfile
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 3.0.0"
      gemfile: .gemfile
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.6.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0.0"
      gemfile: .gemfile
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
      gemfile: .gemfile
gemfile: .gemfile
notifications:
  email:
    - al@lab42.it
